const colors = {
  light: {
    text: '#ffffff',
    tint: '#f59e0b',
    background: '#0d0d0d',
    foreground: '#ffffff',
    card: '#1a1a1a',
    cardForeground: '#ffffff',
    primary: '#f59e0b',
    primaryForeground: '#000000',
    secondary: '#1e1e1e',
    secondaryForeground: '#ffffff',
    muted: '#1e1e1e',
    mutedForeground: '#888888',
    accent: '#f59e0b',
    accentForeground: '#000000',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    border: '#2a2a2a',
    input: '#2a2a2a',
    success: '#22c55e',
    successForeground: '#ffffff',
  },
  dark: {
    text: '#ffffff',
    tint: '#f59e0b',
    background: '#0d0d0d',
    foreground: '#ffffff',
    card: '#1a1a1a',
    cardForeground: '#ffffff',
    primary: '#f59e0b',
    primaryForeground: '#000000',
    secondary: '#1e1e1e',
    secondaryForeground: '#ffffff',
    muted: '#1e1e1e',
    mutedForeground: '#888888',
    accent: '#f59e0b',
    accentForeground: '#000000',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    border: '#2a2a2a',
    input: '#2a2a2a',
    success: '#22c55e',
    successForeground: '#ffffff',
  },
  radius: 12,
};

export default colors;
