// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard-dark/DarkHero.tsx": () => import("../components/mockups/dashboard-dark/DarkHero.tsx"),
  "./components/mockups/dashboard-dark/DarkHeroLiveFeed.tsx": () => import("../components/mockups/dashboard-dark/DarkHeroLiveFeed.tsx")
};
